services:
    database:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
    server:
        build:
            context: .
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
